name: 'Auto Generate Next Release Tag'
description: 'Automatically generate next release tag incrementally with year, month and iteration based on previous release tag.'
author: 'amitsingh-007'
branding:
  color: 'red'
  icon: 'tag'

inputs:
  github_token:
    description: 'Github secrets token'
    required: true
  tag_prefix:
    description: 'Prefix added to the generated release tag'
    required: true
  tag_template:
    description: 'Template format based in which release tag is generated'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
